"""Overview — executive dashboard."""
from __future__ import annotations

import streamlit as st

from components import cards, charts, shell
from core import services
from utils.formatting import inr, num, pct


def render() -> None:
    shell.render_header("Overview", "Dashboard")

    st.markdown(
        """<div class="hero">
               <div class="hero-tag">FinTech &amp; Banking · Machine Learning</div>
               <h2>AI-Powered Financial Risk Assessment</h2>
               <p>Evaluate EMI affordability, loan eligibility and financial risk using
               machine learning. Every assessment runs a gradient-boosted classifier and
               regressor over 37 engineered financial features to return an eligibility
               decision and a maximum safe monthly instalment.</p>
           </div>""",
        unsafe_allow_html=True)

    c1, c2, _ = st.columns([1, 1, 3], gap="small")
    if c1.button("Start EMI Assessment", type="primary", use_container_width=True):
        shell.goto("EMI Assessment")
    if c2.button("Explore Analytics", use_container_width=True):
        shell.goto("Analytics")

    st.markdown("<div style='height:22px'></div>", unsafe_allow_html=True)

    # ---------- platform KPIs (all sourced from real artifacts) ----------
    profile = services.dataset_profile()
    comps = services.load_model_comparisons()
    test = comps.get("test", {})
    ml = services.mlflow_status()

    clf_acc = test.get("clf", {}).get("accuracy")
    reg_rmse = test.get("reg", {}).get("rmse")

    cards.kpi_row([
        {"label": "Financial Profiles", "tone": "neutral",
         "value": num(profile["rows"]) if profile["rows"] else "—",
         "sub": f"{profile['features']} input features · {profile['targets']} targets"
                if profile["features"] else "Dataset unavailable"},
        {"label": "Eligibility Accuracy", "tone": "ok" if clf_acc else "neutral",
         "value": pct(clf_acc) if clf_acc else "—",
         "sub": "Held-out test set" if clf_acc else "Run the notebook to generate"},
        {"label": "EMI Prediction Error", "tone": "ok" if reg_rmse else "neutral",
         "value": f"±{inr(reg_rmse)}" if reg_rmse else "—",
         "sub": "RMSE on held-out test set" if reg_rmse else "Metrics unavailable"},
        {"label": "Tracked Experiments", "tone": "ok" if ml["available"] else "warn",
         "value": num(ml["total_runs"]) if ml["available"] else "—",
         "sub": f"{len(ml['registered'])} models in registry" if ml["available"]
                else "Tracking store unavailable"},
    ])

    st.markdown("<div style='height:22px'></div>", unsafe_allow_html=True)

    left, right = st.columns([1.45, 1], gap="medium")

    with left:
        df = services.load_sample()
        if df is not None:
            st.markdown('<div class="card-title">Portfolio eligibility mix by product</div>',
                        unsafe_allow_html=True)
            st.plotly_chart(charts.scenario_mix(df), use_container_width=True,
                            config={"displayModeBar": False})
        else:
            cards.empty_state("Dataset Unavailable",
                              "The source dataset could not be found in the application "
                              "directory, so portfolio analytics cannot be displayed.")

    with right:
        meta = services.load_models().get("meta", {})
        rows = [
            ("Classification model", meta.get("best_classifier", "—")),
            ("Regression model", meta.get("best_regressor", "—")),
            ("Eligibility classes", "Eligible · High Risk · Not Eligible"),
            ("Lending products", num(profile["scenarios"]) if profile["scenarios"] else "—"),
            ("Engineered features", "37"),
        ]
        cards.panel("Production models", cards.data_rows(rows))

        st.markdown("<div style='height:14px'></div>", unsafe_allow_html=True)

        if test:
            clf_m = test.get("clf", {})
            reg_m = test.get("reg", {})
            rows2 = [
                ("Accuracy", pct(clf_m.get("accuracy"))),
                ("F1 score (macro)", f"{clf_m.get('f1_macro', 0):.3f}"),
                ("ROC-AUC", f"{clf_m.get('roc_auc_ovr', 0):.3f}"),
                ("RMSE", inr(reg_m.get("rmse"))),
                ("R²", f"{reg_m.get('r2', 0):.3f}"),
            ]
            cards.panel("Held-out test performance", cards.data_rows(rows2))
        else:
            cards.panel("Held-out test performance",
                        '<div style="color:#64728C;font-size:0.87rem;">'
                        'Test metrics are generated by the training notebook and were '
                        'not found in the models directory.</div>')

    st.markdown("<div style='height:22px'></div>", unsafe_allow_html=True)

    # ---------- capability summary ----------
    a, b, c = st.columns(3, gap="medium")
    with a:
        cards.panel("Eligibility Assessment",
                    '<div style="color:#8A97AD;font-size:0.885rem;line-height:1.65;">'
                    'Classifies each application as Eligible, High Risk or Not Eligible '
                    'with calibrated class probabilities, supporting risk-based pricing '
                    'rather than binary rejection.</div>')
    with b:
        cards.panel("Affordability Modelling",
                    '<div style="color:#8A97AD;font-size:0.885rem;line-height:1.65;">'
                    'Predicts the maximum monthly instalment an applicant can safely '
                    'service, derived from income, obligations, liquidity and credit '
                    'history.</div>')
    with c:
        cards.panel("Model Governance",
                    '<div style="color:#8A97AD;font-size:0.885rem;line-height:1.65;">'
                    'Every training run is tracked in MLflow with parameters, metrics '
                    'and artifacts. Production models are versioned in the model '
                    'registry for auditability.</div>')
